file(REMOVE_RECURSE
  "CMakeFiles/flight.dir/autocode/sig_kadet_ert_rtw/autocode.cpp.obj"
  "CMakeFiles/flight.dir/autocode/sig_kadet_ert_rtw/autocode.cpp.obj.d"
  "CMakeFiles/flight.dir/datalog_fmu_v2.pb.c.obj"
  "CMakeFiles/flight.dir/datalog_fmu_v2.pb.c.obj.d"
  "CMakeFiles/flight.dir/flight/analog.cc.obj"
  "CMakeFiles/flight.dir/flight/analog.cc.obj.d"
  "CMakeFiles/flight.dir/flight/battery.cc.obj"
  "CMakeFiles/flight.dir/flight/battery.cc.obj.d"
  "CMakeFiles/flight.dir/flight/config.cc.obj"
  "CMakeFiles/flight.dir/flight/config.cc.obj.d"
  "CMakeFiles/flight.dir/flight/datalog.cc.obj"
  "CMakeFiles/flight.dir/flight/datalog.cc.obj.d"
  "CMakeFiles/flight.dir/flight/effectors.cc.obj"
  "CMakeFiles/flight.dir/flight/effectors.cc.obj.d"
  "CMakeFiles/flight.dir/flight/flight.cc.obj"
  "CMakeFiles/flight.dir/flight/flight.cc.obj.d"
  "CMakeFiles/flight.dir/flight/msg.cc.obj"
  "CMakeFiles/flight.dir/flight/msg.cc.obj.d"
  "CMakeFiles/flight.dir/flight/nav.cc.obj"
  "CMakeFiles/flight.dir/flight/nav.cc.obj.d"
  "CMakeFiles/flight.dir/flight/sensors.cc.obj"
  "CMakeFiles/flight.dir/flight/sensors.cc.obj.d"
  "CMakeFiles/flight.dir/flight/sys.cc.obj"
  "CMakeFiles/flight.dir/flight/sys.cc.obj.d"
  "CMakeFiles/flight.dir/flight/telem.cc.obj"
  "CMakeFiles/flight.dir/flight/telem.cc.obj.d"
  "CMakeFiles/flight.dir/flight/vms.cc.obj"
  "CMakeFiles/flight.dir/flight/vms.cc.obj.d"
  "CMakeFiles/flight.dir/usr/local/nanopb/pb_common.c.obj"
  "CMakeFiles/flight.dir/usr/local/nanopb/pb_common.c.obj.d"
  "CMakeFiles/flight.dir/usr/local/nanopb/pb_decode.c.obj"
  "CMakeFiles/flight.dir/usr/local/nanopb/pb_decode.c.obj.d"
  "CMakeFiles/flight.dir/usr/local/nanopb/pb_encode.c.obj"
  "CMakeFiles/flight.dir/usr/local/nanopb/pb_encode.c.obj.d"
  "datalog_fmu_v2.pb.c"
  "datalog_fmu_v2.pb.h"
  "flight"
  "flight.pdb"
  "nanopb/generator/nanopb_generator.py"
  "nanopb/generator/proto/nanopb.proto"
  "nanopb/generator/proto/nanopb_pb2.py"
)

# Per-language clean rules from dependency scanning.
foreach(lang C CXX)
  include(CMakeFiles/flight.dir/cmake_clean_${lang}.cmake OPTIONAL)
endforeach()
