
# Consider dependencies only in project.
set(CMAKE_DEPENDS_IN_PROJECT_ONLY OFF)

# The set of languages for which implicit dependencies are needed:
set(CMAKE_DEPENDS_LANGUAGES
  )

# The set of dependency files which are needed:
set(CMAKE_DEPENDS_DEPENDENCY_FILES
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/datalog_fmu_v2.pb.c" "CMakeFiles/flight.dir/datalog_fmu_v2.pb.c.obj" "gcc" "CMakeFiles/flight.dir/datalog_fmu_v2.pb.c.obj.d"
  "/usr/local/nanopb/pb_common.c" "CMakeFiles/flight.dir/usr/local/nanopb/pb_common.c.obj" "gcc" "CMakeFiles/flight.dir/usr/local/nanopb/pb_common.c.obj.d"
  "/usr/local/nanopb/pb_decode.c" "CMakeFiles/flight.dir/usr/local/nanopb/pb_decode.c.obj" "gcc" "CMakeFiles/flight.dir/usr/local/nanopb/pb_decode.c.obj.d"
  "/usr/local/nanopb/pb_encode.c" "CMakeFiles/flight.dir/usr/local/nanopb/pb_encode.c.obj" "gcc" "CMakeFiles/flight.dir/usr/local/nanopb/pb_encode.c.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/autocode/sig_kadet_ert_rtw/autocode.cpp" "CMakeFiles/flight.dir/autocode/sig_kadet_ert_rtw/autocode.cpp.obj" "gcc" "CMakeFiles/flight.dir/autocode/sig_kadet_ert_rtw/autocode.cpp.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/analog.cc" "CMakeFiles/flight.dir/flight/analog.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/analog.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/battery.cc" "CMakeFiles/flight.dir/flight/battery.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/battery.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/config.cc" "CMakeFiles/flight.dir/flight/config.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/config.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/datalog.cc" "CMakeFiles/flight.dir/flight/datalog.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/datalog.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/effectors.cc" "CMakeFiles/flight.dir/flight/effectors.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/effectors.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/flight.cc" "CMakeFiles/flight.dir/flight/flight.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/flight.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/msg.cc" "CMakeFiles/flight.dir/flight/msg.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/msg.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/nav.cc" "CMakeFiles/flight.dir/flight/nav.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/nav.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/sensors.cc" "CMakeFiles/flight.dir/flight/sensors.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/sensors.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/sys.cc" "CMakeFiles/flight.dir/flight/sys.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/sys.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/telem.cc" "CMakeFiles/flight.dir/flight/telem.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/telem.cc.obj.d"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/flight/vms.cc" "CMakeFiles/flight.dir/flight/vms.cc.obj" "gcc" "CMakeFiles/flight.dir/flight/vms.cc.obj.d"
  )

# Pairs of files generated by the same build rule.
set(CMAKE_MULTIPLE_OUTPUT_PAIRS
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/datalog_fmu_v2.pb.h" "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/datalog_fmu_v2.pb.c"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/nanopb/generator/proto/nanopb.proto" "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/nanopb/generator/nanopb_generator.py"
  )


# Targets to which this target links.
set(CMAKE_TARGET_LINKED_INFO_FILES
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/core-build/CMakeFiles/core.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/checksum-build/CMakeFiles/checksum.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/navigation-build/CMakeFiles/navigation.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/mavlink-build/CMakeFiles/mavlink.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/mpu9250-build/CMakeFiles/mpu9250.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/ublox-build/CMakeFiles/ublox.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/ams5915-build/CMakeFiles/ams5915.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/bme280-build/CMakeFiles/bme280.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/sbus-build/CMakeFiles/sbus.dir/DependInfo.cmake"
  "/home/lorenz/c_drive/spaaro-main_edit/flight_code/build/_deps/sd-build/CMakeFiles/sd.dir/DependInfo.cmake"
  )

# Fortran module output directory.
set(CMAKE_Fortran_TARGET_MODULE_DIR "")
